  db:
    image: postgres:9.6
    container_name: database
    environment:
      POSTGRES_USER: isi
      POSTGRES_PASSWORD: isi
    volumes:
      - ./bdd:/var/lib/postgresql/data
      - ./example.dump:/home/root/local.dump
